### ISSUE TITLE
缺少 InterceptableServiceProvider, Dora.Interception.AspNetCore 无法编译通过 

### ISSUE THREAD

**Issue by tupunco** [jiangjinnan/Dora#1]
# Dora.Interception.AspNetCore
- InterceptionServiceProviderMiddleware.cs(43,39,43,67): error CS0246: 未能找到类型或命名空间名“InterceptableServiceProvider”(是否缺少 using 指令或程序集引用?)

**Comment by jiangjinnan** [comment]
Dora.Interception.AspNetCore 已经不用了！

**Comment by jiangjinnan** [comment]
Dora.Interception.AspNetCore 已经不用了！

**Comment by jiangjinnan** [comment]
Dora.Interception.AspNetCore 已经不用了！

**Comment by tupunco** [comment]
兄弟呀, `root/Dora.sln` 放到这么明显的位置, 居然 `不能用`, 这是在测试 `关注` 这个项目人的 `智商` 呀.

**Comment by jiangjinnan** [comment]
抱歉！已经修改了!

**Comment by eightHundreds** [comment]
@jiangjinnan 个人资料的博客链接写错了
